- include: apt.yml

- name: install misc generic utilities
  apt: package={{item}} state=present
  with_items:
    - chrony
    - curl
    - git
    - jq
    - net-tools
    - procps
    - rsync
    - screen
    - sudo
    - unattended-upgrades
    - wget

- name: configure unattended upgrades
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/ owner=root group=root mode=0644

- name: root user ssh authorized_keys
  authorized_key: user=root
                  key="{{item}}"
  with_file:
    - public_keys/octo
    - public_keys/mfournier
