- name: install various build scripts
  copy: src={{item}} dest=/usr/local/bin/ mode=0755 owner=root
  with_items:
    - make-dist-archive.sh
    - make-rpms.sh
    - make-debs.sh
    - s3-yum-repo.sh
    - s3-apt-repo.sh
