- name: install various build scripts
  copy: src={{item}} dest=/usr/local/bin/ mode=0755 owner=root
  with_items:
    - make-dist-archive.sh
    - make-rpms.sh
    - make-debs.sh
    - s3-yum-repo.sh
    - s3-apt-repo.sh

- name: create DSL-seed workspace
  file: path=/var/lib/jenkins/jobs/DSL-seed/workspace/ state=directory owner=jenkins group=jenkins mode=0775

- name: install jenkins job descriptions
  copy: src={{item}} dest=/var/lib/jenkins/jobs/DSL-seed/workspace/ owner=jenkins group=jenkins mode=0644
  with_items:
    - packages.groovy
