- name: waiting for jenkins plugin update center to settle
  wait_for: path=/var/lib/jenkins/updates/default.json

- name: install required jenkins plugins
  command: curl -vn -XPOST -d '<dummy plugin="{{item.plugin}}@{{item.version}}"/>' http://localhost:8080/pluginManager/installNecessaryPlugins
  args:
    creates: /var/lib/jenkins/plugins/{{item.plugin}}
  notify:
    - restart jenkins
    - waiting for jenkins to reboot
  with_items:
    jenkins_plugins

- name: waiting for jenkins plugins installation to complete
  wait_for: path=/var/lib/jenkins/plugins/{{item.plugin}}
  with_items:
    jenkins_plugins

- meta: flush_handlers
