- name: letsencrypt prefs
  copy: src=letsencrypt.pref dest=/etc/apt/preferences.d/

- name: install letsencrypt
  apt: package=letsencrypt state=present

- name: letsencrypt cli config file
  copy: src=letsencrypt-cli.ini dest=/etc/letsencrypt/cli.ini

- name: letsencrypt cron
  template: src=renew-letsencrypt.sh.j2 dest=/etc/cron.weekly/renew-letsencrypt owner=root group=root mode=0755

