- name: restart jenkins
  service: name=jenkins state=restarted

- name: run Job_DSL_seed
  shell: curl -vn -XPOST http://localhost:8080/job/Job_DSL_seed/build

- name: waiting for jenkins to reboot
  wait_for: port=2222 delay=10
